several fixes and stable indexing

diff --git a/index b/index
--- a/index
+++ b/index
@@ -40,8 +40,8 @@ filetype_icon() {
     { test "$1" = "" } && { 
 	error "filetype_icon called without argument"; return 1 }
 
-    path="$1"
-    filename="${path##*/}"
+    fpath="$1"
+    filename="${fpath##*/}"
 
     ext="${filename##*.}"
     name="${filename%%.*}"
@@ -50,7 +50,7 @@ filetype_icon() {
     # analize extensions, will be overridden by name
     case $ext:l in
 	txt) res=text-plain.png ;;
-	html) res=text-x-html.png ;;
+	html) res=text-html.png ;;
 	xml) res=text-xml.png ;;
 	md5|sha*) res=hash.png ;;
 	asc|gpg) res=signature.png ;;
@@ -79,27 +79,125 @@ filetype_icon() {
     print "$res"
 }
 
-index_dir() {
-    { test -d "$1" } || { error "cannot index: not a directory '$1'"; return 1 }
+index_short() {
+    func "index_long_preview \"$1\" \"$2\" \"$3\""
+    dir="${1}${3}"
+    { test -d "$dir" } || { error "cannot index: not a directory '$dir'"; return 1 }
     files=()
-    ttmp=`ls -l --time-style=long-iso "$1" | awk '
+    ttmp=`ls "$dir" | awk '
 /^total/ { next }
 /^$/ { next }
-{ printf "files+=(\"%s;%s;%s\")", $8, $5, $6 }
+{ printf "files+=(\"$1\");" }
 '`
     { test $? = 0 } || {
-	error "Error parsing directory: $1"
+	error "Error parsing directory: $dir"
+	return 1 }
+    
+    eval "$ttmp"
+    
+    act "${#files} files parsed in $dir"
+
+    diralias="$2"
+    dirbase="$3"
+    # setup paths for test
+    if [ "$CMD" = "test" ]; then
+	LINK_PREFIX="file://${dir}"
+    else
+	LINK_PREFIX="${diralias}${dirbase}"
+    fi
+    func "LINK_PREFIX = $LINK_PREFIX"
+
+    cat <<EOF
+<table class="table table-hover table-condensed">
+<thead><tr>
+<th class="col-sm-1 col-md-1 col-lg-1"><!-- filetype icon --></th>
+<th class="col-sm-3 col-md-4 col-lg-4"><!-- file name --></th>
+</tr></thead>
+EOF
+    
+    for f in ${files}; do
+	name="${f}"
+	ext="${name##*.}" # file extension
+	file="${1}/${name}" # file path
+
+	typefield=""
+	namefield=""
+	previewfield=""
+	link=""
+	icon=""
+	icon_width="width=\"50px\""
+
+	if [ -L "$file" ]; then # is a symlink
+	    if [ -d "$file" ]; then # symlink to folder
+		link="<a href=\"${name}/index${EXTENSION}\">"
+		typefield="${link}<img src=\"${WEB_ROOT}/icons/symlink.png\" alt=\"symlink\" ${icon_width}></a>"
+		namefield="${link}${name}</a>"
+	    else                    # symlink to file
+		link="<a href=\"${LINK_PREFIX}/${name}\">"
+		typefield="${link}<img src=\"${WEB_ROOT}/icons/symlink.png\" alt=\"symlink\" ${icon_width}></a>"
+		namefield="${link}${name}</a>"
+	    fi
+	elif [ -d "$file" ]; then   # is a folder
+	    link="<a href=\"${name}/index${EXTENSION}\">"
+	    typefield="${link}<img src=\"${WEB_ROOT}/icons/folder.png\" alt=\"folder\" ${icon_width}></a>"
+	    namefield="${link}${name}</a>"
+	else                        # is a file
+	    { test "$icon" = "" } && { icon="`filetype_icon ${file}`" }
+	    link="<a href=\"${LINK_PREFIX}/${name}\">"
+	    typefield="${link}<img src=\"${WEB_ROOT}/icons/${icon}\" alt=\"${icon}\" ${icon_width}></a>"
+	    namefield="${link}${name}</a>"
+	fi
+
+	# render it all
+	cat <<EOF
+<tr>
+<td style="vertical-align:middle;">${typefield}</td>
+<td style="vertical-align:middle;font-size:1.5em;word-wrap:break-word">${namefield}</td>
+</tr>
+EOF
+	tpwd="`pwd`"
+	{ test "$icon" = "" } && { continue }
+	popd
+	# copy the icon file
+	{ test -r ${destination}/icons/${icon} } || {
+	    func "copy icon in place: $icon (PWD: `pwd`)"
+	    cp $SYS/icons/$THUMB_SIZE/${icon} \
+		${destination}/icons/${icon}
+	}
+	pushd "$tpwd"
+
+    done
+    print "</table>"
+    
+}
+
+index_long_preview() {
+    func "index_long_preview \"$1\" \"$2\" \"$3\""
+    dir="${1}${3}"
+    { test -d "$dir" } || { error "cannot index: not a directory '$dir'"; return 1 }
+    files=()
+    ttmp=`ls -l --time-style=long-iso "$dir" | awk '
+/^total/ { next }
+/^$/ { next }
+{ printf "files+=(\"%s;%s;%s\");", $8, $5, $6 }
+'`
+    { test $? = 0 } || {
+	error "Error parsing directory: $dir"
 	return 1 }
 
     eval "$ttmp"
 
-    act "${#files} files parsed in $1"
-
+    act "${#files} files parsed in $dir"
+    
+    diralias="$2"
+    dirbase="$3"
     # setup paths for test
-    { test "$destination" = "test" } && {
-	LINK_PREFIX="file://$1"
-	act "LINK_PREFIX = $LINK_PREFIX"
-    }
+    if [ "$CMD" = "test" ]; then
+	LINK_PREFIX="file://${dir}"
+    else
+	LINK_PREFIX="${diralias}${dirbase}"
+    fi
+    func "LINK_PREFIX = $LINK_PREFIX"
     
     # human size dividers
     _mb=$((1024 * 1024))
@@ -132,7 +230,7 @@ EOF
 
 	# format date to human readable form
 	hdate=`date -d "$date" +'%d %b %Y'`
-
+	
 	func "$name \t $size \t $date"
 
 	typefield=""
@@ -140,8 +238,6 @@ EOF
 	previewfield=""
 	link=""
 	icon=""
-
-	nametruncate="${(l:20:: :)${name[1,20]}}"
 
 	preview=`preview_file "$file"`
 
@@ -160,7 +256,7 @@ EOF
 
 	if [ -L "$file" ]; then # is a symlink
 	    if [ -d "$file" ]; then # symlink to folder
-		link="<a href=\"${name}/index.html\">"
+		link="<a href=\"${name}/index${EXTENSION}\">"
 		typefield="${link}<img src=\"${WEB_ROOT}/icons/symlink.png\" alt=\"symlink\" ${icon_width}></a>"
 		namefield="${link}${name}</a>"
 		previewfield="<!-- folder -->"
@@ -171,7 +267,7 @@ EOF
 		previewfield="${link}${preview}</a>"
 	    fi
 	elif [ -d "$file" ]; then   # is a folder
-	    link="<a href=\"${name}/index.html\">"
+	    link="<a href=\"${name}/index${EXTENSION}\">"
 	    typefield="${link}<img src=\"${WEB_ROOT}/icons/folder.png\" alt=\"folder\" ${icon_width}></a>"
 	    namefield="${link}${name}</a>"
 	    previewfield="<!-- folder -->"
@@ -195,6 +291,7 @@ EOF
 EOF
 
 	tpwd="`pwd`"
+	{ test "$icon" = "" } && { continue }
 	popd
 	# copy the icon file
 	{ test -r ${destination}/icons/${icon} } || {
